events {}

http {
    server {
        listen: 8080;
        
        location /auth/ {
            proxy-pass http://user-service:8080;
            
            proxy-set-header Host $host;
            proxy-set-header X-Real-Ip $remote_addr;
            proxy-set-header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy-set-header X-Forwarded-Proto $scheme;
        }
        
        location /users/ {
            proxy-pass http://user-service:8080;
            
            proxy-set-header Host $host;
            proxy-set-header X-Real-Ip $remote_addr;
            proxy-set-header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy-set-header X-Forwarded-Proto $scheme;
        }
        
        location /drivers/ {
            proxy-pass http://driver-service:8080;
            
            proxy-set-header Host $host;
            proxy-set-header X-Real-Ip $remote_addr;
            proxy-set-header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy-set-header X-Forwarded-Proto $scheme;
        }
        
        location /orders/ {
            proxy-pass http://order-service:8080;
            
            proxy-set-header Host $host;
            proxy-set-header X-Real-Ip $remote_addr;
            proxy-set-header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy-set-header X-Forwarded-Proto $scheme;
        }
    }
}