<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Identity.Stores">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.extensions.identity.stores\10.0.1\lib\net10.0\Microsoft.Extensions.Identity.Stores.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
