// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Infrastructure.Persistence;

#nullable disable

namespace OrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260304124710_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Infrastructure.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Latitude")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Street")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Region", "City", "Street", "Apartment", "PostalCode", "Longitude", "Latitude")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.OrderDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationAddressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderDeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDeliveryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAddressId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("SourceAddressId");

                    b.ToTable("OrderDeliveries", (string)null);
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductionPlantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDeliveryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionPlantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.ProductionPlantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("ProductionPlants", (string)null);
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.OrderDeliveryEntity", b =>
                {
                    b.HasOne("OrderService.Infrastructure.Entities.AddressEntity", "DestinationAddress")
                        .WithMany("DestinationOrderDeliveries")
                        .HasForeignKey("DestinationAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderService.Infrastructure.Entities.OrderEntity", "Order")
                        .WithOne("OrderDelivery")
                        .HasForeignKey("OrderService.Infrastructure.Entities.OrderDeliveryEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderService.Infrastructure.Entities.AddressEntity", "SourceAddress")
                        .WithMany("SourceOrderDeliveries")
                        .HasForeignKey("SourceAddressId");

                    b.Navigation("DestinationAddress");

                    b.Navigation("Order");

                    b.Navigation("SourceAddress");
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.OrderEntity", b =>
                {
                    b.HasOne("OrderService.Infrastructure.Entities.ProductionPlantEntity", "ProductionPlant")
                        .WithMany("Orders")
                        .HasForeignKey("ProductionPlantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductionPlant");
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.ProductionPlantEntity", b =>
                {
                    b.HasOne("OrderService.Infrastructure.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.AddressEntity", b =>
                {
                    b.Navigation("DestinationOrderDeliveries");

                    b.Navigation("SourceOrderDeliveries");
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderDelivery");
                });

            modelBuilder.Entity("OrderService.Infrastructure.Entities.ProductionPlantEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
