<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.12.37" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Shared.csproj" />
      <ProjectReference Include="..\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
